### ISSUE TITLE
Auto Away Not Working

### ISSUE THREAD

**Issue by joshchi31** [RocketChat/Rocket.Chat.Electron#1408]
## My Setup
- Operating System: Server is running Ubuntu using Snap, Client is Windows 10, all software fully updated.
- App Version: 2.16.2
- Installation type: .exe direct download from rocket.chat

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Desktop client on Windows does not honor the auto away settings. Clients using the desktop version are either Online if the client is running or Offline if they client is shutdown. They never go into an away state after any amount of idle time. Setting the status to Away manually works as expected.

### Current Behavior
Clients never go into an Away state after the configured "Idle Time Limit" under User Presence when "Enable Auto Away" is enabled.

### Expected Behavior
Client presence should change to Away after the timer limit is reached and the computer is completely idle.

**Comment by ankar84** [comment]
Same issue here with RC.Electron 2.16.0 and RC Server 2.2.1 with 3 instances.
And as new feature it will ne nice if User Presence respect OS lock (Win+L in winodws) and set away in that moments.

**Comment by dbenz04** [comment]
Same issue here, same rocketchat versions. Auto-away works fine in 2.15.5.

I noticed when I went to uninstall 2.16.2, that 2.15.5 was still installed in Add/Remove Programs. I wonder if Rocketchat didn't upgrade properly and that contributed to the auto-away not working?

**Comment by ankar84** [comment]
Fixed in 2.17.0
Both works fine. 
And time auto-away and OS lock (Win+L in winodws) set user presence to Away!
Good work!

**Comment by TheGr8Wonder** [comment]
@tassoevan - With 2.17.7 and server 3.0.2 this issue is still present. Running Win10 1909 x64 fully patched. The moment the system is locked, user stays online indefinitely. Auto away is enabled and their timeout is 60 seconds.  

I see there was additional work done in #1268 that may fix this again.

**Comment by ankar84** [comment]
> With 2.17.7 and server 3.0.2 this issue is still present.

I'm not confirm that.
Just now tested 2.17.7 version on Windows 10 1909 and server 3.0.2
All works great - WIN+L change user status to Away immediately.
I set auto-away timer to 60 sec for test and right after 60 sec of inactivity user status become Away.
So, check you config, reload (CTRL+R) client, reboot computer.

**Comment by TheGr8Wonder** [comment]
Please strike my comment. My system had 2.15.x, 2.16.x, and 2.17.x installed on it according to program files. I removed all 3 and deleted the install destination directory and reinstalled 2.17.7 and the issue went away. Thank you!

**Comment by phlegx** [comment]
Can it be that this is still not working correctly in version 3.1.1? I"m on Ubuntu 18.04 and when the Computer goes to hibernate, the next day when I open it, I see my colleague either always online or always as away. The status that is correctly shown is the offline status.

**Comment by ldklikm** [comment]
> Can it be that this is still not working correctly in version 3.1.1? I"m on Ubuntu 18.04 and when the Computer goes to hibernate, the next day when I open it, I see my colleague either always online or always as away. The status that is correctly shown is the offline status.

This thread is closed. You will not get an answer here. Please open a new thread.
