### ISSUE TITLE
Test desktop notification button doesn't work since 2.17.0

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.Electron#1509]
## My Setup

- Operating System: Windows 10
- App Version: 2.17.5
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
**Test desktop notification** button doesn't work, you press it and nothing happens.
But message notifications itself works fine.
Last version where **Test desktop notification** button works fine is 2.16.2

### Current Behavior
**Test desktop notification** button doesn't work

### Expected Behavior
Test notification should appear as Windows toast notification when press **Test desktop notification** button.

**Comment by JargeZ** [comment]
As far as I managed to find out, the problem is that in the function pass incorrect data
`const response = await fetchWithoutOrigin(avatarUrl);`
 where `avatarUrl` defined as `'/avatar/rocket.cat'`

Because the validation button apparently uses the Notification class directly without processing the onClientMessageReceived event, where the relative link is brought to the correct dataurl format, taking into account the CDN and other settings

**Comment by frdmn** [comment]
Can you guys please try version 2.17.11 which was just released?

The PR #1662 should fix this problem. 😊

**Comment by ankar84** [comment]
> Can you guys please try version 2.17.11 which was just released?

Yeap, test notifications works great in 2.17.11
Thanks @frdmn

**Comment by vidlb** [comment]
No, I'm still having issues with notifications, it does not work properly. The test button is not doing anything, moreover it kills the program.
In the terminal I got this :
```
Error: net::ERR_CONTENT_LENGTH_MISMATCH
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2545:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
```

I'm on Ubuntu 20.04, RC dekstop 2.17.11 (.deb file installed)
