### ISSUE TITLE
Spell check hell : impossible to change language or disable it

### ISSUE THREAD

**Issue by ThomasKientz** [RocketChat/Rocket.Chat.Electron#1520]
### My Setup

- Operating System: 10.15.3 
- App Version: v2.17.7
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Spell check is enabled but probably set to a different language that my system. I can not find a way to disable it or to set the language to french.

Impossible to change the language to French which is in the list and no option to disable spellcheck. 

When I select French and go back, "Default" is still active.
<img width="1354" alt="Capture d’écran 2020-02-14 à 09 50 48" src="https://user-images.githubusercontent.com/10157845/74515960-d97a5c00-4f0f-11ea-85a6-0332a5ff6a43.png">

I have never added any dictionary or anything before.

**Comment by tassoevan** [comment]
Please fill [the issue template](https://raw.githubusercontent.com/RocketChat/Rocket.Chat.Electron/develop/.github/ISSUE_TEMPLATE.md). This info is important to help you.

**Comment by ankar84** [comment]
> v2.17.7
> 
> Impossible to change the language to French which is in the list and no option to disable spellcheck.
> 
> I have never added any dictionary or anything before.

2.17.7 should ask only 2 directory for dictionaries on Windows:
c:\Program Files\Rocket.Chat\resources\dictionaries\
c:\Users\[UserName]\AppData\Roaming\Rocket.Chat\dictionaries\
And shouldn't use system dictionaries.
In my case both true.

**Comment by ThomasKientz** [comment]
@tassoevan done

**Comment by ThomasKientz** [comment]
> Please fill [the issue template](https://raw.githubusercontent.com/RocketChat/Rocket.Chat.Electron/develop/.github/ISSUE_TEMPLATE.md). This info is important to help you.

@tassoevan done

**Comment by tassoevan** [comment]
@ThomasKientz 

> Spell check is enabled but probably set to a different language that my system. I can not find a way to disable it or to set the language to french.

If you right-click in any editable area (e.g. the message composer box), you'll see an `Spelling languages` menu (or `Langages` if French was detected from your operating system). Then you can set then spell checking dictionaries you want to use.

If you have any suggestions to improve this, I'd love to know.

> When I select French and go back, "Default" is still active.

Looks like a bug in the Rocket.Chat server itself. Do you have access to its version?

**Comment by ThomasKientz** [comment]
> If you right-click in any editable area (e.g. the message composer box), you'll see an Spelling languages menu (or Langages if French was detected from your operating system). Then you can set then spell checking dictionaries you want to use.

Was not aware of that! French is not part of the list, how can I add it ?

<img width="351" alt="Capture d’écran 2020-02-14 à 10 17 25" src="https://user-images.githubusercontent.com/10157845/74518238-bce02300-4f13-11ea-9522-51d188708db0.png">

> If you have any suggestions to improve this, I'd love to know.

Maybe an additional setting "spell check language" option ?

Thanks for the support

**Comment by tassoevan** [comment]
I think I've let the `Rechercher un langage ...` disabled on MacOS by mistake (I'm considering patching it right now), but as workaround you can copy a pair of files `[language].aff` and `[language].dic` to `~/Library/Application Support/Rocket.Chat/dictionaries`. I'd recommend https://github.com/wooorm/dictionaries/blob/master/dictionaries/fr/index.aff and https://github.com/wooorm/dictionaries/blob/master/dictionaries/fr/index.dic, renamed as `fr.aff` and `fr.dic`.

**Comment by anne-pacalet** [comment]
On my Ubuntu 16.04, I created the `~/.config/Rocket.Chat/dictionaries/` and imported the two files suggested above, and now I can choose the `fr` language in the `Language` menu, but it does nothing... The spell checking is still in English (`en_US` is always selected each time I open the `Language` menu).

**Comment by strapsi** [comment]
i have the same problem with the windows client (v 2.17.7). if i disable the spell checking it gets enabled the next time i start the rocketchat client and is set to en_US

**Comment by Coriou** [comment]
Same issue as the two above on the Mac client

**Comment by thakilla** [comment]
Yeah it's realy annoying. Choosen language is being reset all the time. (Mac OS)

**Comment by jpele-tis** [comment]
Best way to fix this is to add manually the French or other language dictionnary.
You can download it in LibreOffice project : https://github.com/LibreOffice/dictionaries/tree/master/fr_FR
Download : `fr.aff` and `fr.dic` and place it here : `C:\Program Files\Rocket.Chat\resources\dictionaries`

**Comment by haldyr** [comment]
> Best way to fix this is to add manually the French or other language dictionnary.
> You can download it in LibreOffice project : https://github.com/LibreOffice/dictionaries/tree/master/fr_FR
> Download : `fr.aff` and `fr.dic` and place it here : `C:\Program Files\Rocket.Chat\resources\dictionaries`

For languages with diacritics you need to also convert it to UTF-8.

**Comment by SwampFalc** [comment]
Just FYI: the same issue happens on my 2.17.11 client on Linux. I keep turning spellcheck off (I'm working in a tri-lingual group of people so it's useless) and every time I start the client it resets to en_US.

**Comment by ankar84** [comment]
Fixed in 3.0
![image](https://user-images.githubusercontent.com/4023037/94756213-83273400-039f-11eb-89e6-2e59bc402649.png)

**Comment by juice9990** [comment]
The problem still exists on rocket chat client version 3.0.6. After turning this off by deselecting English and restarting rocket chat, English is by default selected again.

**Comment by ankar84** [comment]
> The problem still exists on rocket chat client version 3.0.6. After turning this off by deselecting English and restarting rocket chat, English is by default selected again.

Why don't you try latest 3.1.1 version?

**Comment by juice9990** [comment]
3.0.6 was the version linked on https://rocket.chat/ but I also checked 3.1.1 later after writing this comment and the problem still exists also on 3.1.1. Also, I thnk there was nothing in the changelog that would suggest this was fixed? I installed an old version of rocket chat - 2.16.2 and this bug is not there.

Also, we use quite old server version 2.0.1 - no time to update it. I guess we will update the server and then I will try the latest client again in few weeks when we find more time.

**Comment by fenjen** [comment]
I can confirm it seems to be impossible to start RocketChat 3.1.1 with a disabled spell checker. I have to do disable spell check manually every time I start RocketChat (every day).

**Comment by juice99** [comment]
It's still happening in the latest Rocket Chat. It is very annoying. Will this ever be fixed?

**Comment by ankar84** [comment]
> It's still happening in the latest Rocket Chat. It is very annoying. Will this ever be fixed?

Not confirm that.
Just tested on 3.5.5 - spell check languages are changing (enable and then disable some of them) and works perfect.

**Comment by fenjen** [comment]
Just downloaded the 3.5.6 and I'm able to disable spell checking now 👍 After a restart, despite en-US is automatically turned back on, RocketChat doesn't show red lines. I don't know whether that is intended, but as long as I can restart without getting red lines, it's fine for me. Thanks!

**Comment by ankar84** [comment]
I don't know. I use only Russian dictionary and every restart I have only that language selected.
So, I'm closing that issue because it solved some versions ago.
![image](https://user-images.githubusercontent.com/4023037/134478964-49bbe7ce-89bb-463a-9823-e33a33282d07.png)
