### ISSUE TITLE
3.0.7 still problems with Jitsi (hosted server) video call

### ISSUE THREAD

**Issue by sandreddu** [RocketChat/Rocket.Chat.Electron#1841]
My Setup
- Operating System: Windows 10 1909
- App Version: 3.0.7
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Description
We host our own Jitsi meet server and Rocketchat server is set up to always open in new window. It works fine until release 2.17.11. Our Jitsi server is set up to use client certificate authentication

### Current Behavior
If I start a video call (in channel or 1-to-1), I'm asked to select a client certificate. It's selected. Then, the new window opens, but remains blank. If I close it and click on Click to Join again, it still opens a blank window. 

![2020-10-22 10_15_33-Window](https://user-images.githubusercontent.com/47738900/96844967-72268b80-1450-11eb-96ea-7ed4f06aaf56.png)

If I close it again and select Click to Join for a THIRD time, it opens the Jitsi meeting window as expected, but the rocketchat client window becomes blank and the only way to return to the regular window after the video call is ended is to reload the client (Ctrl+R)

![2020-10-22 10_17_43-Window](https://user-images.githubusercontent.com/47738900/96844976-75217c00-1450-11eb-91c4-06d219f2f9f1.png)

### Expected Behavior
I select the client certificate, the jitsi window opens and the video call starts and end, and once ended we return to work on Rocket.Chat.

**Comment by johnpugh24** [comment]
I am getting the same behaviour from the same setup, the problem was introduced with version 3.0.0 of the app. Jitsi works on 2.17.11 fine, but fails on anything newer.  It also works using Chrome rather than the app. 

We are using the latest version of Rocketchat server and our Jitsi server is up to date as well.

**Comment by hogthrob** [comment]
Same issue here. Same setup. Works with 2.17.11, works in Chrome but not in Rocket.Chat app 3.0.x including 3.0.4

**Comment by corrigac** [comment]
I am getting similar behaviour on OS/X - with V3.0.3 (Updated) client. Self Hosted RocketChat v3.7.1, Self Hosted Jitsi jitsi-meet-turnserver:amd64 (1.0.4428-1, 1.0.4466-1), jitsi-videobridge2:amd64 (2.1-351-g0bfaac1c-1, 2.1-376-g9f12bfe2-1), jicofo:amd64 (1.0-636-1, 1.0-644-1), jitsi-meet-web:amd64 (1.0.4428-1, 1.0.4466-1), jitsi-meet:amd64 (2.0.5076-1, 2.0.5142-1), jitsi-meet-web-config:amd64 (1.0.4428-1, 1.0.4466-1)

**Comment by danel1** [comment]
Same problem with 3.0.4 on macOS 10.15.7

**Comment by Vringe** [comment]
Same problem here with MacOS 10.15.7 and Client version 3.0.3 (AppStore)

**Comment by fplante-tink** [comment]
I can confirm we are also experiencing the same behaviour both on MacOS 10.15 and Windows 10 regardless of the room setup (1v1, channels, private groups). Also tried updating Jitsi Meet server to the latest release (1.0.4466) - we're self hosted - as well as RocketChat server to 3.7.1 but the probleme's still present. 

The only workaround we found was downgrading the clients to 2.17.11.

**Comment by pompi-stefana** [comment]
Same problem on Windows 10 and Ubuntu desktop clients.
Server version: 3.7.1
Client version: 3.0.4
Jitsi version: 2.0.5142 (recently updated, the behavior was the same on previous version as well, most likely not related to Jitsi).

**Comment by dasfreak** [comment]
possibly related  to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1834?

**Comment by sandreddu** [comment]
Problem persists by release 3.0.5

**Comment by chrisi51** [comment]
With Jitsi 2.0.4966 its still working - even with Rocketchat Client 3.0.5 ... after updating Jitsi Server we also got the white/blank window problem while Rocketchat Client < 3.0.0 is still working

**Comment by stleitner** [comment]
Same problem with Mac App Store Version 3.0.3

**Comment by stleitner** [comment]
and also in Mac DMG Version 3.0.6

**Comment by BSerpent86** [comment]
same issue in the Linux version, although no certificate is used.

**Comment by EnCz** [comment]
We can reproduce this issue on multiple machines, mainly Mac and Linux.

**Comment by sandreddu** [comment]
Problem persists with release 3.0.7. Updated title and issue description

**Comment by merlin-tc** [comment]
I am having exactly the same problem.
Using Rocket.Chat with integrated jitsi server installed via docker.
For authentication I am using JWT.

I just did some tests and downgrading to  *:stable-5076 makes it work again for me.
https://hub.docker.com/r/jitsi/web/tags

It is weird though that browsers seem to work without problem.

**Comment by rollitoJFLO** [comment]
We are also using a self hosted Jitsi docker environment and just like "merlin-tc" above, we also began having issues after upgrading Jitsi containers to version 5142. Issue persisted on older and newer rocketchat clients (browsers were fine). Downgrading Jitsi containers back to 5076 fixed the issues for us. Also using JWT for authentication. 

Clients were on macOS.

**Comment by EnCz** [comment]
@tassoevan Could we get some update here? Is this problem recognized ? Are you going to fix it sometimes soon? This is very annoying for everyone using the client and jitsi :/ It's completely broken

**Comment by corrigac** [comment]
Workaround - don't use the electron client, stick with chrome...

**Comment by EnCz** [comment]
@corrigac 
> Workaround - don't use the electron client, stick with chrome...

Yeah obviously.. but it get's complicated to explain as soon as a business likes to provision the pre-configured client to 500-600 workers where most of them simply aren't tech-savvy ( to say the least :) )

**Comment by chrisi51** [comment]
> @tassoevan Could we get some update here? Is this problem recognized ? Are you going to fix it sometimes soon? This is very annoying for everyone using the client and jitsi :/ It's completely broken

Luckily we got a backup of the jitsi server before we updated so this is actually the simplest solution ... just not updating jitsi until somebody is yelling, that everything works again :P

**Comment by EnCz** [comment]
> > @tassoevan Could we get some update here? Is this problem recognized ? Are you going to fix it sometimes soon? This is very annoying for everyone using the client and jitsi :/ It's completely broken
> 
> Luckily we got a backup of the jitsi server before we updated so this is actually the simplest solution ... just not updating jitsi until somebody is yelling, that everything works again :P

Yea we are going to try to downgrade our jitsi instance to *:stable-5076 like @merlin-tc said. But obviously this is no long-term solution.

**Comment by ankar84** [comment]
We installed 3.0.7 on every managed computer and all was fine, until today...
Today we updated Jitsi components on our self-hosted Jitsi deployment to this versions:
```
jitsi-meet-prosody=1.0.4466-1
jitsi-meet-tokens=1.0.4466-1
jitsi-meet-web=1.0.4466-1
jitsi-meet-web-config=1.0.4466-1
jicofo=1.0-644-1 
jitsi-videobridge2=2.1-376-g9f12bfe2-1
```

and immediately after that we start to experience that problem, but only in desktop client. Like other described that here.
Web and mobile version are not involved.
@tassoevan please fix that critical for a lot of Rocket Chat users bug. Thank you!

**Comment by EnCz** [comment]
As I suggested in my last post we did downgrade our jitsi-web component to *:stable-5076 and the client starts working as intended again. 
This jitsi build is (currently) only 2-3 months old, so it doesn't hurt too much but obviously this is no long-term solution.

And all "This is an open source project" aside: I think it's communications-wise not okay to completely ignore the community here for more than a month now :/ The guys at RocketChat can do better, I'm sure.

**Comment by laliluna** [comment]
This is fixed for us with the latest Jitsi update 2.0.5390-3.

**Comment by Kulfadir** [comment]
> 
> 
> This is fixed for us with the latest Jitsi update 2.0.5390-3.
Yes, same here

**Comment by merlin-tc** [comment]
I just upgraded to the 5390 docker build but I am still having that problem with the RocketChat client   :-(
Using browsers works fine though. So I had to downgrade to jitsi docker image jitsi/web:stable-5076 which is the last one for me without that bug just as mentioned here #issuecomment-726250612

**Comment by bahmanjafari** [comment]
Hi 
my setup :
rocketchat : 3.10.0
own jitsi : latest 

rocketchat and jitsi separately work fine but video-conference  in rocketchat work only on andriod app . when we start call in web or windows client in p2p conversation or channel just popup and shown " Start video call / yes or cancel ? " and then click on yes split page in middle and call windows is white only an not appear anything's  .
 
 but in andriod and ios app when click on start video call open new windows on who create video call and for other show click join to call and just mobile app when click to join after 1 second join in video call and work fine everything's.
 
 but about 90% of we users  use linux and windows app

**Comment by ankar84** [comment]
> my setup :
> rocketchat : 3.10.0
> own jitsi : latest
> 
> rocketchat and jitsi separately work fine but video-conference in rocketchat work only on andriod app . when we start call in web or windows client in p2p conversation or channel just popup and shown " Start video call / yes or cancel ? " and then click on yes split page in middle and call window is white only an not appear anything's .

It's a totally different issue
Please check it https://github.com/RocketChat/Rocket.Chat.Electron/issues/1919#issuecomment-759652092
