### ISSUE TITLE
Message Notification "Default" not show

### ISSUE THREAD

**Issue by korobita** [RocketChat/Rocket.Chat.Electron#2027]
## My Setup

- Operating System: window 10
- App Version: 3.2.0
- Installation type: .exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
RocketChat not show Message Notification when new messenge

**Comment by ankar84** [comment]
Confirm that no notifications on Windows

**Comment by Albvadi** [comment]
Same here.

**Comment by Hativ** [comment]
I have no notifications, too. 3.2.2 on Ubuntu.

**Comment by dieg00uy** [comment]
Same here; 3.2.2 on Windows 10.

**Comment by shoei101** [comment]
no notifications on macOS Big Sur

**Comment by ankar84** [comment]
One interesting thing - I just updated server to most recent stable 3.14 and notifications start working fine.

**Comment by ankar84** [comment]
> One interesting thing - I just updated server to most recent stable 3.14 and notifications start working fine.

I was wrong in that.

At some moment notifications did work properly in 3.2.2
And it was after I updated server to 3.14
And I made a logic conclusion, that server update fixed that notification issue, but it's not.
Not I don't have notifications in desktop Electron client.
Notification in Web version works perfect.

**Comment by FravashY** [comment]
Same here; Electron Client 3.2.2 on Windows 10 20H2, Server 3.14.0.

**Comment by lurch89** [comment]
Also having issues on 3.2.0, upgraded to 3.2.2 with no change. Windows 10 20H2, server 3.13.2. Could also be related/linked to #1858 which also cropped up around the same time.

**Comment by rcadmin19** [comment]
Same problem here. Notifications completely gone. Version 3.1.1 had notifications but nothing happpened when I clicked the notification.
Desktop client: 3.2.2 
OS: Win10 2004
Server: 3.13.2

**Comment by mks-85** [comment]
same here, no desktop notifications at all.....

Operating System: Windows 10 20H2
App Version: 3.2.2
Installation type: exe from github releases, installed as user, and same with msi deployed and installed as admin

**Comment by mikemkm** [comment]
We also have this issue:
- server 3.13.3
- client 3.2.2
Problem did not exist on earlier 3.1.1 client.

**Comment by Nirsa-tistory** [comment]
There was a notification in version 3.1.1, but notification not working in 3.2.2

OS : Windows 10 2004
Server : 3.13.1
Client : 3.2.2

**Comment by changlogi** [comment]
Same here; Electron Client 3.2.2, 3.2.0 on Windows 10 20H2, Server 3.14.0., 3.14.1.

but 3.1.1 on Win10 20H2 is okay

**Comment by ankar84** [comment]
I guess that lots of bugs will be fixed in 3.3.0 and as you can see [here](https://github.com/RocketChat/Rocket.Chat.Electron/pull/2019) work in progress and almost done.

**Comment by ankar84** [comment]
Fixed in 3.3.0

**Comment by ankar84** [comment]
Fixed in 3.2.3 finally via https://github.com/RocketChat/Rocket.Chat.Electron/commit/2d4607dd3bb49dfb27c2df24f6a5b95d0b675ee4
https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.2.3

**Comment by dhemas** [comment]
- Electron Client 3.2.3
- Server 3.15.0
- Windows 10 21H1

Notification still not showing, clicking "Test Desktop Notification" in preferences produces same result

**Comment by ankar84** [comment]
> Notification still not showing, clicking "Test Desktop Notification" in preferences produces same result

Not confirm that.
![image](https://user-images.githubusercontent.com/4023037/124236045-ae050b00-db1e-11eb-8571-a2097e554e24.png)
![image](https://user-images.githubusercontent.com/4023037/124236100-bcebbd80-db1e-11eb-9777-71887736a98b.png)

**Comment by dhemas** [comment]
> > Notification still not showing, clicking "Test Desktop Notification" in preferences produces same result
> 
> Not confirm that.
> ...


https://user-images.githubusercontent.com/23565404/124245386-26cd8c80-db4a-11eb-93b4-97c1f510f7d5.mp4

**Comment by Mystikal57** [comment]
Hi,
same problem for us :-(

**Comment by ankar84** [comment]
> same problem for us :-(

try 3.2.3 please

**Comment by Mystikal57** [comment]
i'm on the last build, client + server

**Comment by ankar84** [comment]
> i'm on the last build, client + server

I don't know. Check your notification settings in RC and at OS system level.
All works fine in 3.2.3 in our deployment.

**Comment by lurch89** [comment]
Confirmed 3.2.3 client shows notifications now. Windows 10 20H2.

**Comment by cazetto** [comment]
Related Issue: #2091
