### ISSUE TITLE
[3.2.2] Linux - Gnome 40 - Desktop notification without content

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat.Electron#2043]
## My Setup

- Operating System: Fedora 34
- App Version: RPM 3.2.2

## Description
![grafik](https://user-images.githubusercontent.com/979342/118499800-8bae5e00-b727-11eb-8eee-e1b6a3c000d5.png)
Desktop notification was showing message in the past. Not is is saying that the server is ready in case of a notification.

### Expected Behavior
Desktop notification should include the received message.

**Comment by tmartincpp** [comment]
In my case I don't even have notifications (using /usr/lib/notification-daemon/notification-daemon).

**Comment by poandlsl** [comment]
I can also confirm that Rocket Chat client 3.2.2 does not show desktop notifications in:
Ubuntu 18.04 (Gnome 3.28.2)
Windows 10 21H1

**Comment by romanyx-bit** [comment]
Same problem here with Rocket Chat client 3.2.2 : Desktop notification no longer shows text of received message
Ubuntu 20.04.2 LTS

Furthermore, 
- The "Test Desktop Notifications" button doesn't work anymore
- A notification appears for ALL message on ALL channel even if "Show Desktop Notifications For" is set to "Mentions"

good luck ;)

**Comment by pesc** [comment]
Same on MacOS with 3.2.2

**Comment by MrMarlin** [comment]
Can confirm. No notifications on Ubuntu 20.04 with KDE

**Comment by Vkat14** [comment]
Upgraded to 3.2.2 2 days ago, no Desktop Notifications. The "Test Desktop Notifications" button does not work either.

**Comment by Forage** [comment]
The original report is about only receiving "RocketChat is ready" notifications, which is the same issue I'm having since the update from 3.1.1 to 3.2.2 as well. This happens with Ubuntu 20.10 and 21.04.
Downgrading to 3.1.1 solves the issue, which makes it a regression for an issue that has been fixed in the past already.

All the people reporting no notifications at all here are possibly dealing with a different issue.

**Comment by Forage** [comment]
Version 3.3.0 gives me a mix of the proper notification with the message content and an additional "RocketChat is ready" notification hiding the first one. Reverting back to 3.1.1 again.

**Comment by tmartincpp** [comment]
This is fixed in 3.2.3 for me :heart:

**Comment by Forage** [comment]
I still get "RocketChat is ready" notifications in 3.2.3, so it's not this bug that is fixed.

**Comment by cazetto** [comment]
Hi, guys. Could you provide us with the information below?

What operating system and which version?
What version of Rocket.Chat (Server)?
Which version of Rocket.Chat (Electron/Desktop)?

**Comment by cazetto** [comment]
> Same on MacOS with 3.2.2

@pesc could you please give us more information on what exactly is going on for you?

**Comment by cazetto** [comment]
For macOS users, check if the notification for Rocket.Chat is enabled in the system preferences as in the image below:

<img width="679" alt="Screen Shot 2021-08-10 at 16 20 48" src="https://user-images.githubusercontent.com/230598/128922469-5ec1d0f8-3052-4227-98f1-e3c6a5b81d0e.png">

**Comment by pesc** [comment]
> > Same on MacOS with 3.2.2
> 
> @pesc could you please give us more information on what exactly is going on for you?

Fixed in 3.2.3 for me

**Comment by MrMarlin** [comment]
> Can confirm. No notifications on Ubuntu 20.04 with KDE

fixed for me in 3.2.3
