### ISSUE TITLE
Cannot log with custom OAuth provider after updating the client to v3.4.0

### ISSUE THREAD

**Issue by infra-monkey** [RocketChat/Rocket.Chat.Electron#2133]
**Describe the bug**
When trying to login with a custom OAuth provider (keycloak), The login popup doesn't show up. 
The dev console shows this error:
d229bcc9aa214889724d7c90b55cad16497088aa.js?meteor_js_resource=true:772 Uncaught TypeError: Cannot read property 'focus' of null
    at o (d229bcc9aa214889724d7c90b55cad16497088aa.js?meteor_js_resource=true:772)
    at Object.u.showPopup (d229bcc9aa214889724d7c90b55cad16497088aa.js?meteor_js_resource=true:772)
    at u.launchLogin (d229bcc9aa214889724d7c90b55cad16497088aa.js?meteor_js_resource=true:772)
    at Object.<anonymous> (d229bcc9aa214889724d7c90b55cad16497088aa.js?meteor_js_resource=true:971)
    at c (d229bcc9aa214889724d7c90b55cad16497088aa.js?meteor_js_resource=true:5)
    at Object.n [as launchLogin] (d229bcc9aa214889724d7c90b55cad16497088aa.js?meteor_js_resource=true:5)
    at p.requestCredential (d229bcc9aa214889724d7c90b55cad16497088aa.js?meteor_js_resource=true:971)
    at Function.a.<computed> (d229bcc9aa214889724d7c90b55cad16497088aa.js?meteor_js_resource=true:971)
    at Function.overrideLoginMethod (d229bcc9aa214889724d7c90b55cad16497088aa.js?meteor_js_resource=true:971)

What operating system and which version? Linux Fedora 34 latest (X11)
Which version of Rocket.Chat (Server)? 3.17.2
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.4.0 (flatpak)
Is there any setting relevant changed?
Just the rocketchat client update

**To Reproduce**
1. Go to 'login page'
2. Click on 'The custom oauth login button'
4. Nothing happens

**Expected behavior**
The login popup should apear and process to the login

**Screenshots**
![image](https://user-images.githubusercontent.com/43171889/131311144-ec36c0be-bd72-44d6-b008-b32bb64bcbdb.png)

**Additional context**
It was working before the desktop client update.
Loging with a local user works in the desktop client.
Loging with the custom OAuth provider works in the browser.

**Comment by infra-monkey** [comment]
Workaround: rollback to version 3.2.3 of the flatpak release:
sudo flatpak update --commit=6796daeda4a065b9e5e9ec7bff6a418106df8e866149dd19158624bbd57905df chat.rocket.RocketChat
With 3.2.3 I can login again

**Comment by ankar84** [comment]
Wow! I confirm that critical issue!
![image](https://user-images.githubusercontent.com/4023037/131319288-5eb59509-ea08-4cc6-8cfc-28e7b5b09427.png)
We have similar deployment with KeyCloak and it is impossible to sign-in in 3.4.0 version of Electron app.

**Comment by infra-monkey** [comment]
@ankar84 I have tested only on linux flatpak version. Do you use other os or package type?

**Comment by ankar84** [comment]
> Do you use other os or package type?

Yes, I'm using Electron app on Windows environment - currently Windows 10 1909
Guess bug in code, not in environment

**Comment by ankar84** [comment]
> Workaround: rollback to version 3.2.3

Confirm that workaround on WIndows!
1. Downgrade to 3.2.3
2. Login via KeyCloak
3. Update to 3.4.0
4. User is on server

**Comment by wreiske** [comment]
We are affected by this issue as well 🙈

**Comment by xi-ao** [comment]
There's a similar issue with latest Ferdi release : https://github.com/getferdi/ferdi/issues/1828

**Comment by ankar84** [comment]
3.5.0 still have that issue

**Comment by ankar84** [comment]
I guess that problem could be with SSO mechanism where no separate new window create like it happens on machines where SSO not applicable. So, there is no window and focus is undefined in that case.

**Comment by davinkevin** [comment]
Same problem, I had to go back to version 3.1.1 to be able to log in.

**Comment by deridiot** [comment]
Can confirm the issue on 3.4 and 3.5 as well. We are running our own keycloak server. Error is as described above. It works fine when connecting to a different rocketchat server that uses the build in login mechanism. So it seems definitely related to oath in some way.

**Comment by ankar84** [comment]
3.5.1 issue still here.

**Comment by tkyser-rodeo** [comment]
Surely we can get a dev to chime in on this. An update or something. I grow weary of dealing with the fallout this has caused at my org.

**Comment by wreiske** [comment]
Yeah, we've got a lot of employees that are not happy about this being broken and our executive team is questioning the reliability of Rocket.Chat :(. An update would be appreciated.

**Comment by tkyser-rodeo** [comment]
We threw a lot of weight behind Rocket.Chat as an alternative to Slack, Teams, Mattermost, etc... and this is really hurting its long term viability. 

I totally get the FOSS part and we aren't ungrateful for the impact its had on the open source community. Nevertheless for their enterprise components to be considered for purchase at a premium, evaluation begins with the core features, and I promise it doesn't bode well if issues like this pop up and go for days without even an acknowledgement.

Sure the alternatives cost a ton and have their own quirks, but to a sizable company issues like this one cost a comparable if not greater amount in resources to handle.

**Comment by cazetto** [comment]
As the npm packages including Electron have been updated, it may have generated some issues.

We are looking at authentication-related issues right now and hope to have good news soon.

**Comment by ggazzo** [comment]
should be fixed at 3.5.2

**Comment by wreiske** [comment]
![NAaV7hjMyG](https://user-images.githubusercontent.com/6295044/132636188-f53acf08-48ed-4e19-a0c8-d061e71b1c59.gif)

Sadly, this did not fix the issue on 3.5.2.

![image](https://user-images.githubusercontent.com/6295044/132636249-28bdea17-0df7-4275-b311-b2990d8c538d.png)

**Comment by ggazzo** [comment]
thanks @wreiske need to check in another machine, believe or not its working here =/

**Comment by deridiot** [comment]
Yeah have to confirm 3.5.2 is sadly not working for our setup. Same issue as before.

**Comment by ankar84** [comment]
Confirm, that issue not fixed
![image](https://user-images.githubusercontent.com/4023037/132653458-c6360e41-985c-4b7b-a057-508cf8ec1201.png)

**Comment by ggazzo** [comment]
3.5.3? 😬

**Comment by wreiske** [comment]
Confirmed Google Login is working again in 3.5.3! 🥳 Thank you @ggazzo !

**Comment by ankar84** [comment]
Yeap! Confirm that issue fixed in 3.5.3!
Thank you, team!
