### ISSUE TITLE
Desktop app crash, when open sub-menu

### ISSUE THREAD

**Issue by Guihudge** [RocketChat/Rocket.Chat.Electron#2221]
### Description:

Using a snap version of desktop, when open sub-menu, sub-menu are blank and app freeze. System window open and ask to wait or force kill app, and after a short time app close it self. 

### Steps to reproduce:

1. Open sub-menu and try to navigate inside.

### Expected behavior:

Correct display of sub menu, and fix crash.

### Actual behavior:
![Screenshot from 2021-11-06 12-39-53](https://user-images.githubusercontent.com/8157398/140608333-a7cf6d15-e6ce-4a78-931e-ab6ee34ebbe2.png)

### Server Setup Information:

- Version of Rocket.Chat Server: Unknown (hosting by an organization)
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: version 3.2.2 (snap)
- Operating System: ArchLinux, Kernel 5.14.16 (x86_64), gnome 40.4.0 (Wayland)

### Additional context

PS: Sorry for my bad English, I'm french.

### Relevant logs:
Log on terminal:
`[bugsnag] Loaded!
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "rocketchat" setting to invalid value "Rocket.Chat.desktop"
/usr/share/libdrm/amdgpu.ids: No such file or directory
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
/usr/share/libdrm/amdgpu.ids: No such file or directory
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
[1]    5213 segmentation fault (core dumped)  rocketchat-desktop
`

**Comment by jeanfbrito** [comment]
The Snap is updated and I think that the problem is solved. If it remains, please reopen the issue and tell us.
Thank you!

**Comment by Guihudge** [comment]
The issue is not solved, but now we have more details on terminal, after open an sub-menu I got this:

```
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "rocketchat" setting to invalid value "Rocket.Chat.desktop"
/usr/share/libdrm/amdgpu.ids: No such file or directory
[5796:0113/114809.831371:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[bugsnag] Loaded!
[5718:0113/114812.737135:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[5718:0113/114812.741879:ERROR:object_proxy.cc(642)] Failed to call method: org.gnome.ScreenSaver.GetActive: object_path= /: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/”
[5718:0113/114839.847679:ERROR:command_buffer_proxy_impl.cc(328)] GPU state invalid after WaitForGetOffsetInRange.
[5718:0113/114839.908584:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=512
/usr/share/libdrm/amdgpu.ids: No such file or directory
[1]    5718 segmentation fault (core dumped)  snap run rocketchat-desktop
[5909:0100/000000.010559:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

```
And the app exited with SEGV (139) code

**Comment by jeanfbrito** [comment]
> The issue is not solved, but now we have more details on terminal, after open an sub-menu I got this:
> 
> ```
> Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "rocketchat" setting to invalid value "Rocket.Chat.desktop"
> /usr/share/libdrm/amdgpu.ids: No such file or directory
> [5796:0113/114809.831371:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
> [bugsnag] Loaded!
> [5718:0113/114812.737135:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
> [5718:0113/114812.741879:ERROR:object_proxy.cc(642)] Failed to call method: org.gnome.ScreenSaver.GetActive: object_path= /: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/”
> [5718:0113/114839.847679:ERROR:command_buffer_proxy_impl.cc(328)] GPU state invalid after WaitForGetOffsetInRange.
> [5718:0113/114839.908584:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=512
> /usr/share/libdrm/amdgpu.ids: No such file or directory
> [1]    5718 segmentation fault (core dumped)  snap run rocketchat-desktop
> [5909:0100/000000.010559:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
> ```
> 
> And the app exited with SEGV (139) code

Is this with the 3.7.5 version?

**Comment by jeanfbrito** [comment]
Please test if the problem persists with our latest release. I will be closing the issue but if there is any problem yet, we will open it again.

**Comment by arkhamvm** [comment]
```
$ uname -a
Linux username 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```
```
$ snap list | grep rocket
rocketchat-desktop              3.8.13                      672     latest/stable  rocketchat**    -
```
```
$ rocketchat-desktop 
[805824:0418/135439.117145:ERROR:node_bindings.cc(276)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "rocketchat" setting to invalid value "Rocket.Chat.desktop"

(rocketchat-desktop:805824): Gtk-WARNING **: 13:54:39.967: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
[bugsnag] Loaded!
[805824:0418/135442.395385:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.401" (uid=1000 pid=805824 comm="/snap/rocketchat-desktop/672/rocketchat-desktop --" label="snap.rocketchat-desktop.rocketchat-desktop (enforce)") interface="org.freedesktop.login1.Manager" member="Inhibit" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=962 comm="/lib/systemd/systemd-logind " label="unconfined")
```
