### ISSUE TITLE
Notification doesn't work anymore after updated to version 3.9.7

### ISSUE THREAD

**Issue by 0xb10ckdev** [RocketChat/Rocket.Chat.Electron#2738]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Operating System Version

macOS 11.6.4

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

3.9.7

### Rocket.Chat Server Version

4.8.3

### Describe the bug

Notification was working well on 3.9.6.
Once I updated it to 3.9.7, it stopped sending notification as well as badges.

### How to Reproduce

1. Update Rocket Chat to 3.9.7
2. Receive new messages

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by mgadek007** [comment]
Windows the same :(

**Comment by danel1** [comment]
Same here (macOS 13.5.2)..

@tassoevan @jeanfbrito

**Comment by brlarini** [comment]
I'm on Windows 10 and the notification behavior has changed (to an annoying way).
Up to 3.9.6 the Windows notification pops up then goes away after a few seconds.

On 3.9.7 they don't go away anymore: they go on stacking on the right side, but now below then there's a "close" button (not the usual arrow to the right).
You have to close every. single. notification. manually.

Had to revert to 3.9.6 because I couldn't find a way to get the notification but make it go away automatically.

It this an intended behavior? Is there an internal option to change this on Rocket Chat client?

**Comment by dexter69** [comment]
I have the same on Fedora Linux 38...

**Comment by Romich777** [comment]
The same

**Comment by serious-snow** [comment]
The same, macOS 13.5.2 (22G91) M2 Pro

**Comment by drdelaney** [comment]
Same with Win10 after the client upgrade.  Server is 4.3.3.  Downgraded the client to 3.9.6 and now is back to normal.

**Comment by jeanfbrito** [comment]
Hello, I apologize for any inconvenience caused by the recent changes that broke support for 4.x server versions. While this was not intended, it's important to note that we have officially ended support for Server 4.8.7 as of January 2023.

We fixed the issue, and a release is forthcoming. However, please be aware that similar issues may occur in the future and may not be addressed. For uninterrupted use of the updated official desktop app, we highly recommend updating to a supported server version.

For more information on our support structure and version durability, you can refer to the following link: [Rocket.Chat Support Structure](https://docs.rocket.chat/resources/rocket.chats-support-structure/enterprise-support-and-version-durability/)

**Comment by ojhwel** [comment]
I'm using the 3.9.9 client with server 5.4.10 and this notification issue persists, in my case on Windows. The tray does not show a red dot, the taskbar icon doesn't blink. I realize that 5.4.10 is past end-of-life but it's still the most current LTS version which is why my admin cow orkers don't want to update yet.

**Comment by ebyrne242** [comment]
> I'm using the 3.9.9 client with server 5.4.10 and this notification issue persists, in my case on Windows. The tray does not show a red dot, the taskbar icon doesn't blink. I realize that 5.4.10 is past end-of-life but it's still the most current LTS version which is why my admin cow orkers don't want to update yet.

@ojhwel All current versions of RC are now supported for 6 months, per https://www.rocket.chat/blog/deprecation-notice-cloud-services-mobile-and-desktop-apps-for-legacy-unsupported-versions
They don't specify exactly what release this starts with, but I would assume with 6.3 based on the release date.
