### ISSUE TITLE
Right mouse click not working

### ISSUE THREAD

**Issue by Zerocool56** [RocketChat/Rocket.Chat.Electron#393]
## My Setup

 - __My OS name and version__:  Windows 7 Pro
 - __My current app version__:  2.5.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

When the text is highlighted, the right-click context menu of the copy / paste does not open.

#### Expected Behavior

Should open a context menu for copy / paste

**Comment by shubham95** [comment]
can you send GIF Because when i test it work fine
![isssue](https://cloud.githubusercontent.com/assets/5495227/24028403/dd9ca0d4-0a8b-11e7-8d63-3d44ed9f2a4a.png)

**Comment by Zerocool56** [comment]
Are you kidding me?
How i can do gif with nothing? (http://g.recordit.co/dHzdmlAf8v.gif)

And this problem is present on Linux version too.

**Comment by pmesolution** [comment]
I have the same issue on Ubuntu 16.04 with the Desktop-rocketchat snap app.

**Comment by gdelavald** [comment]
The issue has been fixed in the latest version.

**Comment by Zerocool56** [comment]
In which version?
Current version - 2.8.0 and this issue is still persist.

**Comment by gdelavald** [comment]
This is fixed in 2.9.0 version which should be released shortly.
