### ISSUE TITLE
Using Alt+Shift to change input language opens the Rocket.Chat menu on linux

### ISSUE THREAD

**Issue by vbogdanov** [RocketChat/Rocket.Chat.Electron#50]
I regularly use `Alt+Shift` to change input languages. On my Linux box (kubuntu 15.04) pressing `Alt+Shift` results in the Rocket.Chat menu item being open in addition to changing the input language. As a result I have to press `Alt+Shift, Esc` to continue the input (which is slower and not a habit). 

This might be an Electron issue, I haven't tested with other Electron apps. I haven't tested on Windows either.

**Comment by sampaiodiego** [comment]
I think this should be an Electron issue. I mean it is not rocket.chat who opens menu on <kbd>alt</kbd> press.

**Comment by vbogdanov** [comment]
Just a note - I can't reproduce it with any of the other menu elements or with other key combinations including Alt (or Alt alone).

**Comment by vetash** [comment]
+1

**Comment by ALeschinsky** [comment]
I have the same problem with Slack :rage:

**Comment by vetash** [comment]
Atom also based on electron and does not have this problem. It's really annoying, anybody has a solution?

**Comment by vetash** [comment]
@sampaiodiego Thank you very much!

**Comment by MurzNN** [comment]
Is there any issue about this in electron repository?

**Comment by idanielblake** [comment]
Appeared in Rocketchat+ Version 2.10.1 again

**Comment by msva** [comment]
@idanielblake as well as in new Slack versions, lol.

// although, looks like the real source of the issue is in Electron#11106 (like it's mentioned above)

**Comment by msva** [comment]
@sampaiodiego Can you re-apply the fix again, please? // and add the comment for future developers to DON'T REMOVE THE ANCHORS IN ANY REASON

**Comment by ebrahim** [comment]
I hit this bug on Rocket.Chat+ version 2.10.5 on Debian Stretch amd64.

**Comment by Manyaka** [comment]
I have this bug on 2.10.5 rocket chat desktop, linux mint 18, this bug very annoing, please, fix it

**Comment by wrwrwrr** [comment]
Reintroduced since 2.16.0

**Comment by eugene-rom** [comment]
No workaround? Very annoying in current 3.5.7.

**Comment by MurzNN** [comment]
Electron issue https://github.com/electron/electron/issues/28088 is fixed, so we need update Electron to ^13.1.0 to have this bug solved.

**Comment by eugene-rom** [comment]
@MurzNN Just updated to version 3.7.0 which states "Update Electron 16.0.2" in changes, but issue still there.

**Comment by eugene-rom** [comment]
Updated to version 3.8.5, issue still there.

**Comment by isaacvonaaron** [comment]
Still happening with Electron 18, Arch, X
Doesn't happen on Wayland
