### ISSUE TITLE
Missing file extension when downloading attachment

### ISSUE THREAD

**Issue by jthomae1** [RocketChat/Rocket.Chat.Electron#536]
## My Setup
- Operating System: macOS Sierra
- App Version: Version 2.9.0

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description

To reproduce the issue, try downloading an attachment you received from another user

### Current Behavior

File extension is missing. The issue only occurs with version 2.9.0 of Rocket.Chat+.

### Expected Behavior

File extension should be there. ;)

**Comment by vcapretz** [comment]
hey @jthomae1 @ledainam can you please check if it's not an upload issue? 
I was checking this and every file I uploaded a file it was download correctly, both on RC and on electron app.
but when uploading a file and removing the extension from file's name when being asked to give it a name caused the file to be saved without an extension. 

I thought it probably would be a good idea to force an extension to be included on file upload, but @rodrigok pointed out that some file can indeed exist without an extension (ie `.bash_profile`), and if the user who uploaded it removed the extension it's his responsibility to upload it again with the correct extension

**Comment by ledainam** [comment]
@vcapretz : i think it is upload issue. 
1. When i upload from mobile client ( android, iOs) file upload stuck at 0% or run too slow. i run 4 instance and when i run only 1 instance, it works fine. maybe it issue by running multiple instance. 
2. For misssing extension, user report that when upload from macOS client, it always missing extension. Upload from Windows client is fine.

**Comment by gdelavald** [comment]
@geekgonecrazy I think you have a better insight on the multiple instances upload, can you give @ledainam a quick answer?

**Comment by ledainam** [comment]
@gdelavald : would you like to tell us when this bug will resolve ? Our users reported everytime he lost extension when download attachment at macOS/
Thanks.

**Comment by gdelavald** [comment]
@ledainam This was fixed in the server repository, you can check the PR [here](https://github.com/RocketChat/Rocket.Chat/pull/8296) and will be released in version 0.59.0

**Comment by ledainam** [comment]
@gdelavald : Thanks you so much.

**Comment by ledainam** [comment]
@gdelavald : i updated to 0.59.1. It still missing extension when downloading files.

**Comment by KervyN** [comment]
We have the same issue.
Reproduction: 
Open finder, go to the settings -> adv. setting -> disable "show all file suffix" (the top checkbox)

Workaround:
Open finder, go to the settings -> adv. setting -> check "show all file suffix" (the top checkbox)

Only happens in the Client.

**Comment by gdelavald** [comment]
Thanks for the additional information @KervyN we will work on a fix for this special case

**Comment by lukasmejia** [comment]
Hi there, same issue on macOSX (High Sierra) Client, missing extensions when downloading files, any updates on this?

**Comment by p8107406332** [comment]
hey i want to contribute to this issue can i

**Comment by gdelavald** [comment]
@lukasmejia @p8107406332 Can you guys try and reproduce this in the latest server version (Rocket.Chat 0.59.3)?

**Comment by lukasmejia** [comment]
@gdelavald I'm running on snap (0.59.2) no updates available yet...

**Comment by maximecharron** [comment]
I'm running the latest Docker image on version 0.59.3 and we are having the same issue.

**Comment by p8107406332** [comment]
Ok I will  try

**Comment by gdelavald** [comment]
Snap is being updated today, we included a fix for some cases and it might resolve the issue

**Comment by lukasmejia** [comment]
Great will check later today...

**Comment by lukasmejia** [comment]
@gdelavald Snap updated (0.59.3), still no extension on macOS client

**Comment by lukasmejia** [comment]
Hi guys, Any updates on this???

**Comment by gdelavald** [comment]
@lukasmejia seems like the bugfix for the server didn't fix the issue, we'll investigate further if it's related to the app at all.

**Comment by lukasmejia** [comment]
@gdelavald Thanks!

**Comment by engelgabriel** [comment]
can you please test https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/2.12.1 ?

**Comment by jthomae1** [comment]
The file extensions are attached, but the download window breaks, if you expand the advanced download view. I don't know since when, I just noticed it.

Before expanding: 
![bildschirmfoto 2018-08-15 um 08 55 06](https://user-images.githubusercontent.com/8523176/44135358-0b3b00ca-a069-11e8-8138-63cf5768a11f.png)

After:
![bildschirmfoto 2018-08-15 um 08 55 23](https://user-images.githubusercontent.com/8523176/44135365-1070f4b4-a069-11e8-8e84-9575e5523b15.png)

If you cancel the download, and try it again, the advanced view opens correctly. But the view breaks again, if you want to go back to the standard download view (first screenshot).

Before reducing:
![bildschirmfoto 2018-08-15 um 09 00 40](https://user-images.githubusercontent.com/8523176/44135553-c8d767ea-a069-11e8-9af1-1f11ee4272cc.png)

After:
![bildschirmfoto 2018-08-15 um 09 01 09](https://user-images.githubusercontent.com/8523176/44135562-d9883da8-a069-11e8-8251-175da2fe2dfe.png)


Should I report this bug in a new issue? This one could be closed so far, the attaching of file extensions is working correctly.

**Comment by tassoevan** [comment]
@jthomae1 Please, open a new one. However, this seems to be a Electron bug; I'll investigate it.
