### ISSUE TITLE
Show notifications across Servers

### ISSUE THREAD

**Issue by NickBusey** [RocketChat/Rocket.Chat.Electron#63]
I have two servers setup, one for work, one for family.

Whenever I'm focused on one in the desktop app, notifications for the other go completely unnoticed. I'll click back over to the other server and Whoa! There's a ton of messages waiting over here that I had no idea about.

I want to get notifications for any server I'm logged into, regardless of whether I'm 'focused' on it or not.

**Comment by graywolf336** [comment]
I believe that was part of https://github.com/RocketChat/Rocket.Chat.Electron/pull/52, which was closed for some reason. But I agree, it would be nice to have notifications from all servers added.

**Comment by NickBusey** [comment]
At the very least, there should be a number badge showing unread notices on any other servers. Is this part of the Rocket.Chat core? Or is this only relevant to Electron? I'd love to contribute on this issue if needed.

**Comment by SloMusti** [comment]
This is a problem also for my use case, internal and external work chat.

**Comment by litewhatever** [comment]
Same here.

**Comment by SloMusti** [comment]
Latest beta seems to support this function, so this ticket is fixed as far as I am concerned.

**Comment by litewhatever** [comment]
Yes, seems to be working just fine :+1:

**Comment by NickBusey** [comment]
@SloMusti would you mind sharing where you found the latest beta? I'm on 0.0.9 and it's still not working.

**Comment by litewhatever** [comment]
@NickBusey https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by NickBusey** [comment]
Yup, works for me in the latest. Thanks guys!
